version: '2.0'
services:
  app:
    depends_on:
    - redis
    build: .
    volumes:
    - .:/app
    - ./var/:/fogger
    environment:
      SOURCE_DATABASE_URL: postgresql://user:pass@source:5432/bitpesa_admin_development
      TARGET_DATABASE_URL: postgresql://user:pass@target:5432/bitpesa_admin_development
      REDIS_URL: redis://redis
  worker:
    depends_on:
    - redis
    build: .
    volumes:
    - .:/app
    - ./var/:/fogger
    environment:
      SOURCE_DATABASE_URL: postgresql://user:pass@source:5432/bitpesa_admin_development
      TARGET_DATABASE_URL: postgresql://user:pass@target:5432/bitpesa_admin_development
      REDIS_URL: redis://redis
    restart: always
    command: fogger:consumer --messages=200
  redis:
    image: redis:4
  source:
    volumes:
    - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      POSTGRES_DB: source
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
    image: postgres
  target:
    environment:
      POSTGRES_DB: bitpesa_admin_development
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
    image: postgres
