version: '2.0'
services:
  app:
    depends_on:
    - redis
    build: .
    volumes:
    - .:/app
    - ./var/:/fogger
    environment:
      # SOURCE_DATABASE_URL: postgresql://user1:pass@source:5432/bitpesa_api_development
      # TARGET_DATABASE_URL: postgresql://user1:pass@target:5432/bitpesa_api_development
      SOURCE_DATABASE_URL: postgresql://kevinsmith@host.docker.internal:5432/bitpesa_admin_development
      TARGET_DATABASE_URL: postgresql://kevinsmith@host.docker.internal:5432/testing
      REDIS_URL: redis://redis
  worker:
    depends_on:
    - redis
    build: .
    volumes:
    - .:/app
    - ./var/:/fogger
    environment:
      # SOURCE_DATABASE_URL: postgresql://user1:pass@source:5432/bitpesa_api_development
      # TARGET_DATABASE_URL: postgresql://user1:pass@target:5432/bitpesa_api_development
      SOURCE_DATABASE_URL: postgresql://kevinsmith@host.docker.internal:5432/bitpesa_admin_development
      TARGET_DATABASE_URL: postgresql://kevinsmith@host.docker.internal:5432/testing
      REDIS_URL: redis://redis
    restart: always
    command: fogger:consumer --messages=200
  redis:
    image: redis:4
  # source:
  #   environment:
  #     POSTGRES_DB: bitpesa_api_development
  #     # POSTGRES_DB: postgresql://host.docker.internal:5432/bitpesa_api_development
  #     # POSTGRES_PASSWORD:
  #     POSTGRES_USER: kevinsmith
  #   image: postgres
  # target:
  #   environment:
  #     POSTGRES_DB: bitpesa_api_development
  #     POSTGRES_PASSWORD: pass
  #     POSTGRES_USER: user1
  #   image: postgres
